import re
from typing import *
from wordfreq import word_frequency

STOPWORDS = [
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "'t",
    "'s",
    "should",
    "now",
]


def get_words(t: str, include_stop_words: bool = True) -> List[str]:
    t = re.sub('(\(.*?\))', '', t.lower())
    t = re.sub('(\'\w+)', '', t)  # get rid of 's 't 'll etc
    filter_out = [] if include_stop_words else STOPWORDS
    return [w for w in re.findall('(\w+)', t) if w not in filter_out]


def get_lowest_freq_word(text: str, include_stop_words: bool = True) -> Optional[str]:
    words_freqs = [(w, word_frequency(w, 'en')) for w in get_words(text, include_stop_words=include_stop_words)]
    if len(words_freqs) == 0:
        return None
    return min(words_freqs, key=lambda x: x[1])[0]
